name: kokoro-fastapi-cpu
services:
  kokoro-tts:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
    volumes:
      - ../../api:/app/api
    ports:
      - "8880:8880"
    environment:
      - PYTHONPATH=/app:/app/api
      - ONNX_NUM_THREADS=8
      - ONNX_INTER_OP_THREADS=4
      - ONNX_EXECUTION_MODE=parallel
      - ONNX_OPTIMIZATION_LEVEL=all
      - ONNX_MEMORY_PATTERN=true
      - ONNX_ARENA_EXTEND_STRATEGY=kNextPowerOfTwo
      - API_HOST=0.0.0.0
      - API_PORT=8880
      - USE_GPU=false
      - USE_ONNX=false
      - PHONEMIZER_ESPEAK_PATH=/usr/bin
      - PHONEMIZER_ESPEAK_DATA=/usr/share/espeak-ng-data
      - ESPEAK_DATA_PATH=/usr/share/espeak-ng-data
      - MODEL_DIR=src/models
      - VOICES_DIR=src/voices/v1_0
      - WEB_PLAYER_PATH=/app/web

  # gradio-ui:
  #   image: ghcr.io/remsky/kokoro-fastapi-ui:v0.2.0
  #   build:
  #     context: ../../ui
  #   ports:
  #     - "7860:7860"
  #   volumes:
  #     - ../../ui/data:/app/ui/data
  #     - ../../ui/app.py:/app/app.py
  #   environment:
  #     - GRADIO_WATCH=True
  #     - PYTHONUNBUFFERED=1
  #     - DISABLE_LOCAL_SAVING=false
  #     - API_HOST=kokoro-tts
  #     - API_PORT=8880
